env:
  hostip: 10.7.21.15
  tempestdir: /home/ubuntu/lis-tempest
  osuser: admin
  ostenant: admin
  ospassword: Passw0rd
  network: 
    ssh: 32fad6ab-119e-4809-a3cc-32ed43a540d5
    public: public
  hyperv:
    user: Administrator
    pass: Passw0rd
    scriptdir: \\localhost\scripts

image:
  name: cirros-cloudimg
  external: false
  addr: http://example.com/vhd/centos.vhd

test:
  name: core
  aggregate: 2012R2
  logdir: /home/ubuntu/lis-tempest-logs
  list: tests-sample.list
  parallel: $false