env:
  hostip: 10.7.21.15
  tempestdir: /users/ubuntu/lis-tempest
  logdir: /users/ubuntu/lis-tempest-logs
  osuser: admin
  ostenant: admin
  ospassword: Passw0rd
  network: 
    ssh: private
    public: public

image:
  name: centos64-cloudimg-amd64-vss
  image_location

test:
  testname: core
  aggregate: 2012R2
  testfile:
  
hyperv:
  username:
  password:
  scriptfolder:
  
