env:
  hostip: 10.7.21.15
  tempestdir: /users/ubuntu/lis-tempest
  logdir: /users/ubuntu/lis-tempest-logs
  osuser: admin
  ostenant: admin
  ospassword: Passw0rd
  network: 
    ssh: private
    public: public
  hypervcompute:
    username: Administrator
    password: Passw0rd
    scriptfolder: c:\scripts

image:
  name: centos64-cloudimg-amd64-vss
  external: false
  externaladdr: http://example.com/vhd/centos.vhd

test:
  testname: core
  aggregate: 2012R2
  testfile: storage-tests.txt
  

  
