env:
  hostip: 10.7.21.15
  tempestdir: /users/ubuntu/lis-tempest
  logdir: /users/ubuntu/lis-tempest-logs
  osuser: admin
  ostenant: admin
  ospassword: Passw0rd
  network: 
    ssh: private
    public: public
  hyperv:
    user: Administrator
    pass: Passw0rd
    scriptdir: c:\scripts

image:
  name: centos64-cloudimg-amd64-vss
  external: false
  addr: http://example.com/vhd/centos.vhd

test:
  name: core
  aggregate: 2012R2
  file: storage-tests.txt
  

  
